### PR TITLE
Allow the bullet train js client to respect api variable

### PR DESCRIPTION
**Pull request by amammay**
Something small i found when i was setting up the full stack for bullet train on our own custom domains.

### CODE REVIEW

**Comment by amammay** [comment]
Sounds good, i will implement it as Project.bulletTrainClientAPI and make the updates across the files that will need a reference to it.

**Comment by kyle-ssg** [comment]
Awesome cheers for helping out on this!

**Comment by kyle-ssg** [comment]
Awesome, thanks @amammay!

**Comment by kyle-ssg** [comment]
Just to let you know this is now also in our production code, thanks again @amammay 🚀 .

**Pull request merged**
